### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by dusanvita** [printdotio/printio-android-sdk#152]
Hi everyone, another issue:

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1500)
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1518)
       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
       at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:613)
       at android.support.v4.app.DialogFragment.show(DialogFragment.java:139)
       at hnsv.b()
       at print.io.ActivityProducts$5.run()
       at java.lang.Thread.run(Thread.java:818)

**Comment by vladopajic** [comment]
Hello @dusanvita,

What version of SDK is used?

Thanks,
Vlado

**Comment by vladopajic** [comment]
Fixed in v3.1.15.
