### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by dusanvita** [printdotio/printio-android-sdk#154]
Version 3.1.0

AndroidRuntime: FATAL EXCEPTION: Thread-747
Process: me.keepy, PID: 10061
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1500)
at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1518)
at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:613)
at android.support.v4.app.DialogFragment.show(DialogFragment.java:139)
at xrir.b(Unknown Source)
at print.io.superactivities.SuperActivityCustomize$17.run(Unknown Source)
at java.lang.Thread.run(Thread.java:818)

**Comment by tobiasfrier** [comment]
@dusanvita Thank you for reporting this.

We'll get right now this.

**Comment by bomberaya** [comment]
@dusanvita Any steps to reproduce this?

**Comment by dusanvita** [comment]
@bomberaya well, I can't really say, it just happened once on this particular screen, you may find a clue in SuperActivityCustomize, and since it's an "onSaveInstanceState" might be by putting the app in background or something like that, but it's not the first time or place for IllegalStateException to occur, there's also one more bug I reported with the version 3.0.4.

**Comment by vladopajic** [comment]
Hello @dusanvita,

All `IllegalStateException` that have occurred so far should be fixed. Please, integrate latest SDK (v3.3.0) and report back to us if you find new crashes.

Thanks,
Vlado
