### ISSUE TITLE
Like button on products page: IllegalStateException: Could not execute method for android:onClick

### ISSUE THREAD

**Issue by dusanvita** [printdotio/printio-android-sdk#162]
Tested on v3.1.28 but also existed in the versions before. Occurs on any tested phone and is reproducible with Keepy v2.92.0g available on the play store.

java.lang.IllegalStateException: Could not execute method for android:onClick
  at android.view.View$DeclaredOnClickListener.onClick(View.java:4452)
  at android.view.View.performClick(View.java:5198)
  at android.view.View$PerformClick.run(View.java:21147)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5417)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.reflect.InvocationTargetException
  at java.lang.reflect.Method.invoke(Native Method)
  at android.view.View$DeclaredOnClickListener.onClick(View.java:4447)
  at android.view.View.performClick(View.java:5198) 
  at android.view.View$PerformClick.run(View.java:21147) 
  at android.os.Handler.handleCallback(Handler.java:739) 
  at android.os.Handler.dispatchMessage(Handler.java:95) 
  at android.os.Looper.loop(Looper.java:148) 
  at android.app.ActivityThread.main(ActivityThread.java:5417) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
Caused by: java.lang.NullPointerException: uriString
  at android.net.Uri$StringUri.<init>(Uri.java:475)
  at android.net.Uri$StringUri.<init>(Uri.java)
  at android.net.Uri.parse(Uri.java:437)
  at print.io.ActivityProducts.onClickBottomBarLike(Unknown Source)
  at java.lang.reflect.Method.invoke(Native Method) 
  at android.view.View$DeclaredOnClickListener.onClick(View.java:4447) 
  at android.view.View.performClick(View.java:5198) 
  at android.view.View$PerformClick.run(View.java:21147) 
  at android.os.Handler.handleCallback(Handler.java:739) 
  at android.os.Handler.dispatchMessage(Handler.java:95) 
  at android.os.Looper.loop(Looper.java:148) 
  at android.app.ActivityThread.main(ActivityThread.java:5417) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by bomberaya** [comment]
Have you set the Facebook Page URL?
Use the `PIOConfig.setFacebookPageUrl(String url)` method.
I now see that it is missing from the documentation and it will be added soon.
Thanks

**Comment by bomberaya** [comment]
@dusanvita Also try using the latest version from develop branch which was just updated.

**Comment by nzinyangwa** [comment]
I new learner in android development during runtime of my app i got this error
java.lang.IllegalStateException: Could not execute method for android:onClick
Here is my class backgroundWorker.java code
Where trying  to trace the error from logcat shows me that the problem might be in onPreExecute()
package com.example.innocent.myphpapp;

import android.app.AlertDialog;
import android.content.Context;
import android.os.AsyncTask;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLEncoder;

public class backgroundWorker extends AsyncTask<String,Void,String> {
    Context context;
    AlertDialog alertDialog;
    backgroundWorker (Context context){
        context = context;
    }
    @Override
    protected String doInBackground(String... params) {
        String type =params[0];
        String login_url="http://192.168.43.179/login.php";
        if(type.equals("login")){

                try {
                    String username = params[1];
                    String password = params[2];
                    URL url = new URL(login_url);
                    HttpURLConnection httpURLConnection =(HttpURLConnection)url.openConnection();
                    httpURLConnection.setRequestMethod("POST");
                    httpURLConnection.setDoOutput(true);
                    httpURLConnection.setDoOutput(true);
                    OutputStream outputStream = httpURLConnection.getOutputStream();
                    BufferedWriter bufferedWriter = new BufferedWriter(new OutputStreamWriter(outputStream,"UTF-8"));
                    String post_data = URLEncoder.encode("username","UTF-8")+"="+URLEncoder.encode(username,"UTF-8")+"&"
                            +URLEncoder.encode("password","UTF-8")+"="+URLEncoder.encode(password,"UTF-8");
                    bufferedWriter.write(post_data);
                    bufferedWriter.flush();
                    bufferedWriter.close();
                    outputStream.close();
                    InputStream inputStream = httpURLConnection.getInputStream();
                    BufferedReader bufferedReader =new BufferedReader( new InputStreamReader(inputStream,"iso-8859-1"));
                    String result = "";
                    String line ="";
                    while ((line =bufferedReader.readLine())!=null){
                        result += line;
                    }
                    bufferedReader.close();
                    inputStream.close();
                    httpURLConnection.disconnect();
                    return result;
                } catch (MalformedURLException e) {
                    e.printStackTrace();
                } catch (IOException e) {
                    e.printStackTrace();
                }

        }
        return null;
    }

    @Override
    protected void onPreExecute() {
        alertDialog = new AlertDialog.Builder(context).create();
        alertDialog.setTitle("Login Status");

    }

    @Override
    protected void onPostExecute(String result) {
        alertDialog.setMessage(result);
        alertDialog.show();

    }

    @Override
    protected void onProgressUpdate(Void... values) {
        super.onProgressUpdate(values);
    }
}

**Comment by bomberaya** [comment]
Hi @nzinyangwa, welcome to GitHub :)

I recommend that you start your search at https://stackoverflow.com,
as this (GitHub) is not a site for Questions and Answers.

Try looking there and I'm sure you will find your answer.


On a quick look, your issue might be that the `context` in your `backgroundWorker` is null,
or that the issue is not in that class at all, but you should look at the onClick() method of the button that is used to start the backgroundWorker.

I can't help much more than this, sorry.
