### ISSUE TITLE
High: Payment verification failed message although the payment was successful, + crash

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-android-sdk#90]
Made a payment Paypal. After waiting for about a minute, I received a "Payment verification failed" message. However I checked our Paypal account and the Print.io dashboard and the payment and order were received. 

Also, I tapped OK and the app crashed. 

Log: 
10-27 16:45:50.942    9192-9192/com.photobucket.android E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.photobucket.android, PID: 9192
    java.lang.IllegalStateException: Could not execute method of the activity
            at android.view.View$1.onClick(View.java:3823)
            at android.view.View.performClick(View.java:4438)
            at android.view.View$PerformClick.run(View.java:18422)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Method.invoke(Native Method)
            at android.view.View$1.onClick(View.java:3818)
            at android.view.View.performClick(View.java:4438)
            at android.view.View$PerformClick.run(View.java:18422)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
            at print.io.ActivityPaymentMethod.onClickOk(Unknown Source)
            at java.lang.reflect.Method.invoke(Native Method)
            at android.view.View$1.onClick(View.java:3818)
            at android.view.View.performClick(View.java:4438)
            at android.view.View$PerformClick.run(View.java:18422)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)

![unnamed 1](https://cloud.githubusercontent.com/assets/8051364/4801019/3710454e-5e2c-11e4-97bd-2820667dbc24.png)

**Comment by KuchelD** [comment]
Hi,

I'm integrating Paypal in my Android app and I see the same message listed in the screen shot above ie "Your order did not properly connect etc".

I can see the order in PayPal Sandbox was received OK, and the Print.io Staging Server also receives the order OK with the order in the PrePayment status. 

Basically same problem.

I am testing the new app in Staging Mode with my staging key and my PayPal client staging Key.

I assume it could be an issue with my paypal config since itscam did not respond.  Any ideas?

**Comment by KuchelD** [comment]
I assume this problem could related to the PayPal Sandbox Instant Payment Notification URL?

My test PayPal account currently has IPN disabled.  To enable this feature, I need to enter a 'Notification URL' used by PIO.

I could not see this IPN URL mentioned in the doco. DO you use IPN in the app and if so what is the URL?

**Comment by AustenB** [comment]
David,

I believe this is as far as the staging environment will allow. If you get
to this step than it is working - and you should test with a live order in
production. You can always cancel the order as well.

Best,

Austen

On Fri, Apr 24, 2015 at 7:04 AM, David Kuchel <notifications@github.com>
wrote:

> I assume this problem could related to the PayPal Sandbox Instant Payment
> Notification URL?
>
> My test PayPal account currently has IPN disabled. To enable this feature,
> I need to enter a 'Notification URL' used by PIO.
>
> I could not see this IPN URL mentioned in the doco. DO you use IPN in the
> app and if so what is the URL?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-android-sdk/issues/90#issuecomment-95896732>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio
